# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e929ed8fc7b82083f6f2c45c20bae8d7bbe2e51855b0e51de9b85e6f439f0ad32241c8ea0de833d83f6ef220fd552771daaf90d399eceaa5a0f92c1bf2f4abb

test:
  secret_key_base: 52befbee2c85090d86b16e895fcb693f60849bdf6d46434ac73136dfa440976d4d17c2f7848e92e0a8fc024ea7037360d442829bd74bd87d78ba579ce15e9947

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
